Stripping ANSI to fix ugly error format
swc-project/swc-playground pull request #19
Opened 2022-05-27 18:52 UTC by edwincoronado

Since SWC adopted Miette, the error formatting renders unescaped control chars and ANSI encoding. I attempted to render the nice ANSI colors but Monaco editor suprisignly [does not support this](https://github.com/microsoft/vscode/issues/38834), so I opted to just strip out ANSI. 

Before:
<img width="436" alt="Screen Shot 2022-05-27 at 11 49 32 AM" src="https://user-images.githubusercontent.com/7434954/170772939-a7595d35-16db-4496-bd2c-635c2de487c5.png">

After:
<img width="411" alt="Screen Shot 2022-05-27 at 11 52 35 AM" src="https://user-images.githubusercontent.com/7434954/170773001-bc775695-6f3e-463a-b0bc-5341e8ac2c69.png">

2022-05-30 07:02 UTC, kdy1 requested changes
Can you update lockfile?

2022-05-30 07:07 UTC, g-plane commented
@kdy1 Can we do some refactorings on the `@swc/wasm-web` package then let it return concrete error message and error location. Playground can use that to render error itself.

2022-05-30 07:15 UTC, kdy1 commented
@g-plane Do you mean returning the error as json?
It's possible

2022-05-30 07:44 UTC, g-plane commented
Yes.

2022-05-30 23:31 UTC, edwincoronado commented
> Can you update lockfile?

Done.

2022-05-30 23:33 UTC, edwincoronado commented
> @kdy1 Can we do some refactorings on the `@swc/wasm-web` package then let it return concrete error message and error location. Playground can use that to render error itself.

+1 on this. It'd be useful to have access to the error data without having to parse the Miette output format for applications that are using SWC as an integration point.

2022-05-31 02:06 UTC, g-plane requested changes
Have you formatted with Prettier?

2022-05-31 02:21 UTC, edwincoronado commented
> Have you formatted with Prettier?

just did

2022-05-31 02:21 UTC, g-plane approved these changes
Thanks!

2022-06-08 04:24 UTC, merged