FIX: Add maximum character limit to shared code parameter to URL
swc-project/swc-playground pull request #23
Opened 2022-08-19 13:59 UTC by buraksakalli

## Problem

- When user has a long code and tries to report an issue, GitHub throws a `bad request` error.

![image](https://user-images.githubusercontent.com/10114716/185634369-2f9cfd18-16fc-4673-8167-e81d7b26c6d0.png)

## Solution
- When a user tries to share a long code example, then will see the message. `Your input is too large to share. Please copy the code and paste it into the issue.`

2022-08-19 13:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc-playground?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc-playground?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc-playground?pullRequest=23) it.</sub>

2022-08-19 14:04 UTC, g-plane commented
If user input exceeds limitation, a toast should be popped up, instead of modifying the text.

2022-08-19 16:24 UTC, buraksakalli commented
Hi @g-plane, can you please check it now?

2022-08-20 00:35 UTC, g-plane requested changes

2022-08-20 00:35 UTC, g-plane commented on src/components/InputEditor.tsx
> +  reportUrl.searchParams.set('code', code.length > 2000 ? '' : code)
Why do you clear the code? Whether the code is too long or not, it shouldn't be modified.

2022-08-20 00:35 UTC, g-plane commented on src/components/InputEditor.tsx
> +            // as="a"
If we don't need, remove the code instead of commenting it.

2022-08-20 00:35 UTC, g-plane commented on src/components/InputEditor.tsx
> +    window.open(issueReportUrl, '_blank')
It doesn't make sense that popping up a toast after open a new link.

2022-08-21 15:39 UTC, g-plane approved these changes

2022-08-21 15:40 UTC, merged