feat: 🎸 ast-offset fix
swc-project/swc-playground pull request #9
Opened 2021-12-27 12:17 UTC by IWANABETHATGUY

fix #1

2021-12-27 12:23 UTC, IWANABETHATGUY commented
hi @g-plane , the last pr commit history is pretty messy, so I reopen here, this pull request use no `any` and only one cast https://github.com/swc-project/swc-playground/pull/9/files#diff-39cc19ac7b95ec6821d23f87ff94218f89b639e42d335fa5d17e09cb2cf404fcR74 which is necessary

2021-12-27 14:34 UTC, g-plane requested changes
1. Identifiers must follow camel case convention.
2. Don't use `any`.
3. Those imported and not used as values must be marked as "type-only import".

2021-12-27 16:09 UTC, IWANABETHATGUY commented
> 1. Identifiers must follow camel case convention.
> 2. Don't use `any`.
> 3. Those imported and not used as values must be marked as "type-only import".

sorry about that , recently i write rust a lot, hhhh.

2021-12-28 11:23 UTC, g-plane commented on src/components/Workspace.tsx
> +    keys.forEach((key) => {
Personally using `Object.entries` could be better.

2021-12-28 11:51 UTC, g-plane approved these changes
LGTM, thanks!

2021-12-28 11:52 UTC, merged